### ISSUE TITLE
Update on status

### ISSUE THREAD

**Issue by jeaye** [seantempesta/cljsrn-re-frame-workers#2]
Are you still using this and does it still work with iOS (and have you tested Android)? I think this is a superb idea and would be interested in getting this into my project, specifically on Android.

**Comment by seantempesta** [comment]
Unfortunately, no.  I found depending on the underlying project `react-native-workers` to be unreliable so I moved away from this.  I think the idea is sound though if you are willing to spend the time getting it to work.  I saw wonderful performance and zero UI lag when I was using it.

**Comment by A-Helberg** [comment]
Hey @seantempesta, nice work on this!

Do you mind updating the Readme to include what you mentioned above, as a clojure newbie I spent the last few hours trying to get this to work thinking I did something wrong 😅 and I just realized it was `react-native-workers` so I came here looking for a solution (ps. if you don't have the time, I'm happy to open a PR)

**Comment by seantempesta** [comment]
Done!  Did you get it working?
